# -*- coding: utf-8 -*-
"""Retirados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PmbzNFkmtl8UE4UHn8mvQiIPsgNMwk5K
"""

#####paquete básicos ##
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""##Cargar base de datos y eliminar columnas innecesarias"""

from google.colab import drive
drive.mount('/content/drive')

# se carga la base de datos
df_retirados = pd.read_csv("/content/drive/MyDrive/COLAB/retirement_info.csv") # se carga la base de datos
df_retirados

###Se eliminan columnas innecesarias
df_retirados = df_retirados.drop(columns=['Unnamed: 0.1'])
df_retirados = df_retirados.drop(columns=['Unnamed: 0'])
df_retirados

###Verificar lectura correcta de los datos
df_retirados.sort_values(by=['EmployeeID'],ascending=1).head(100)

"""##Analizar la información de la base de datos, nulos y tipo de variables"""

df_retirados.info()

##Se cambia el tipo de variable retirementDate a fecha
df_retirados['retirementDate']=pd.to_datetime(df_retirados['retirementDate'])

##Se cambia el tipo de variable EmployeeID a categorica
df_retirados = df_retirados.astype({'EmployeeID': object})

##Se cuentan los nulos
df_retirados.isnull().sum()

##Se cambian los nulos de la columna resignationReason por 'Others'
df_retirados['resignationReason'] = df_retirados['resignationReason'].fillna('Others')

df_retirados.isnull().sum()

"""##Contar cada variable y graficar"""

#Contar los valores unicos de Attrition
df_retirados['Attrition'].value_counts()

#Contar los valores unicos de retirementType
df_retirados['retirementType'].value_counts()

#Contar los valores unicos de resignationReason
df_retirados['resignationReason'].value_counts()

##Contar los valores unicos de retirementDate
df_retirados['retirementDate'].value_counts()

#Agregar nueva columna para agrupar fechas por año
#Fecha_año = df_retirados
#Fecha_año['Año'] = pd.DatetimeIndex(Fecha_año['retirementDate']).year
#Fecha_año.groupby("Año").count().agg("EmployeeID")

#Gráfico de pastel retirementType
retirementType = df_retirados["retirementType"].value_counts()

# Crear un gráfico de pastel
plt.figure(figsize=(8, 8))  # Tamaño del gráfico
plt.pie(retirementType, labels= retirementType.index, autopct='%1.1f%%', startangle=140)  # Crear gráfico de pastel
plt.axis('equal')  # Aspecto de círculo
plt.title("Porcentaje de tipo de retiro")  # Título del gráfico

plt.show()

#Gráfico de pastel resignationReason
resignationReason = df_retirados["resignationReason"].value_counts()

# Crear un gráfico de pastel
plt.figure(figsize=(8, 8))  # Tamaño del gráfico
plt.pie(resignationReason, labels= resignationReason.index, autopct='%1.1f%%', startangle=140)  # Crear gráfico de pastel
plt.axis('equal')  # Aspecto de círculo
plt.title("Porcentaje de razon de retiro")  # Título del gráfico

plt.show()